Debug: false
Effects:
  Rainbow:
    colors: "Red-Gold-Green-Aqua"
    interval: 10 #Ticks
  Flashy:
    interval: 10
Items:
  White:
    list:
      - 'DEFAULT' #Default color for all items.
  Red:
    list:
      - 'REDSTONE'
